### PR TITLE
Begin splitting InflowWind_ReadInput into separate subroutines for re…

### PR DESCRIPTION
**Pull request by JakeNunemaker**
…ading and parsing.

**Complete this sentence**
THIS PULL REQUEST IS NOT READY TO MERGE

**Feature or improvement description**
Revises the input pathways for InflowWind to allow for input data to be passed in without relying on file based IO.

**Related issue, if one exists**
<Link to a related GitHub Issue.>

**Impacted areas of the software**
InflowWind.

**Additional supporting information**
<Add any other context about the problem here.>

**Test results, if applicable**
<Add the results from unit tests and regression tests here along with justification for any failing test cases.>

### CODE REVIEW

**Comment by JakeNunemaker** [comment]
This isn't complete but I was hoping to get some feedback partway through the process. So far, InflowWind_ReadInput has b een modified similarly to the Stc module and InflowWind_ParseInput has been started (up through the general section of the input file). This does not include any echo file functionality yet either.

**Comment by andrew-platt** [comment]
Cool!  It looks like good progress!  I think you are on the right track here.

I also noticed the `Frmt` string is never used, so you can delete it.  I have no idea what that was leftover from. InflowWind_Subs [line 174](https://github.com/andrew-platt/openfast/pull/8/files#diff-c2de0a3eff1afda3d2c261ccb1bb4b64R174)

**Comment by rafmudaf** [comment]
To Do List:

- [ ] Wind Type 2

**Comment by rafmudaf** [comment]
To Do List:

- [x] Wind Type 2
- [x] Returning early in some sections so deal with those

**Comment by andrew-platt** [comment]
I completed testing of this and it it passes all the regression tests with changing the key names for TurbSim and Uniform Filenames

- Filename -> UniformFilename   (Uniform section)
- Filename -> TurbSimFilename  (TurbSim section)

**Pull request merged**
